const PARAS = [
  'WE CREATED THIS PROJECT OUT OF NECESSITY. WE LOVE WATCHING MOVIES WITH OUR GRANDMAS, BUT NOTHING RUINS THIS WHOLESOME EXPERIENCE FASTER THAN AN AWKWARD SEX SCENE.',
  "THIS TOOL ALLOWS YOU TO SEARCH (PRETTY MUCH) ANY MOVIE AND FIND OUT IF IT'S GRANDMA SAFE CONTENT.",
  "YOU DON'T EVEN NEED A GRANDMA TO USE THIS TOOL. IT WORKS JUST AS GOOD IF YOU'RE WATCHING A MOVIE WITH YOUR PARENTS.",
  "RATING DATA IS FROM REAL USER REVIEWS (THAT WE SWIPED FROM IMDB.COM) SO DON'T BLAME US IF ITS WRONG.",
]

export default function AboutPage() {
  return (
    <main className="about-page">
      {PARAS.map((text, i) => (
        <p key={i} className="about-page__para">
          {text}
        </p>
      ))}
    </main>
  )
}
